name: Deploy to VPS

on:
  push:
    branches:
      - 2nd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and deploy
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << 'EOF'
        rm -rf hyper
        git config --global user.email yashoswal18@gmail.com 
        git config --global user.name mergebot
        git clone https://github.com/Itzmeproman/hyper.git
        cd hyper
        git fetch origin
        git checkout 2nd
        git pull origin 2nd
        docker build -t 2nd .
        docker stop hyper2 || true
        docker rm hyper2 || true
        docker run -d --name hyper2 -p 1881:1881 hyper
        EOF
